### ISSUE TITLE
Question about Few Things and Thank you for supporting this! <3

### ISSUE THREAD

**Issue by ashfidable** [GabrieleTorini/godot-behavior-tree#7]
So, I have been looking into different behavior trees and everything to jumpstart. This is probably the best I have seen so far and loving the constant support. I tried few behaviors with timer and it's pretty fun to see the flow right on the tree.
I will start with the questions:

- Why did you opt for **physics_frame** and **idle_frame** approach than _normal process_ and _physics_process_? Not going to lie, I am loving this and did learn a new thing. Are they even different from godot's own built in functions (idle = process, physics = physics_process)?

- I created this custom patrol behaviour (it's barebones right now) but I keep getting assertion failed because of "not running()". The code is below.

**go_to_position.gd**
```swift
extends BTLeaf

func _tick(agent: Node, blackboard: Blackboard) -> bool:
	var ag = agent as Agent
	ag.move_towards_position(Vector2(85, 190), blackboard.get_data('delta'))
	if ag.global_position.distance_to(Vector2(85, 190)) <= 50:
		return succeed()
	return running()
```
**agent.gd**
```swift
extends KinematicBody2D
class_name Agent

export (NodePath) var blackboard_path
export (float) var speed

onready var blackboard = get_node_or_null(blackboard_path)
onready var sprite: Sprite = $Sprite

var velocity: Vector2

func _ready():
	blackboard.set_data('position', $Node/Position2D.global_position)

func _physics_process(delta):
	blackboard.set_data('delta', delta)

func move_towards_position(target_position: Vector2, delta: float):
	print(target_position)
	var difference = (target_position - position).normalized()
	velocity = move_and_slide(difference * speed, Vector2.UP)
	velocity.normalized()
```
_I am pretty sure it's my mistake, if so.. I would love to know fix and few pointers based on the script. You have been massive help to my workflow, I would love to continue using this._

**Comment by GabrieleTorini** [comment]
First of all, thanks for the kind words! I'm glad to see this tool is helping someone and I'm doing my best to improve it and address everything.

As for you first question, in the next version I'm going to switch to the _physics_process and _process functions, because what I did there doesn't make much sense :) 

About your problem, right now the way to leave a node running is not to call run(), which is called automatically at each tick(by the way, running() is to check whether it is running), but to yield() for something. 
In fact, since run() is called automatically, if you yield() the tree will automatically understand that the node is running and progressively suspend the execution of all the higher nodes for optimization.
Your leaf then must only return either succeed() or fail(). If you yield(), then the node must be running().

With that being said, here are a few alternatives to make this work:

**go_to_position.gd**
```swift
extends BTLeaf

var check_frequency = 0.1 # seconds
var ag: Agent # Useless optimization
var destination: Vector2 = Vector2(85, 190)

func _tick(agent: Node, blackboard: Blackboard) -> bool:
	ag = agent
	ag.move_towards_position(destination, blackboard.get_data('delta'))
	while ag.global_position.distance_to(destination) > 50:
		yield(get_tree().create_timer(check_frequency, false), "timeout")
	return succeed()
```

or

**go_to_position.gd**
```swift
extends BTLeaf

var ag: Agent # Useless optimization
var destination: Vector2 = Vector2(85, 190)

func _tick(agent: Node, blackboard: Blackboard) -> bool:
	ag = agent
	ag.move_towards_position(destination, blackboard.get_data('delta'))
	if ag.global_position.distance_to(destination) <= 50:
		succeed()

	return fail() # You could think of not reaching the goal as a failure.
```

or, let's change the way we think of it a little bit. The action is successful if you move, not if you reach the goal.

**agent.gd**
```swift
func move_towards_position(target_position: Vector2, delta: float) -> Vector2:
	print(target_position)
	var difference = (target_position - position).normalized()
	velocity = move_and_slide(difference * speed, Vector2.UP)
	#velocity.normalized() # I'm not sure what the purpose of this is, it return a new Vector2 but it is not assigned to anything.
        return velocity
```
**go_to_position.gd**
```swift
extends BTLeaf

var ag: Agent # Useless optimization
var destination: Vector2 = Vector2(85, 190)

func _tick(agent: Node, blackboard: Blackboard) -> bool:
      ag = agent
      var velocity = ag.move_towards_position(destination, blackboard.get_data('delta'))
      blackboard.set_data("distance_to_destination", agent.global_position.distance_to(destination))

       if velocity.length() > 1: # If we moved
		return succeed()
        else:
                return fail()
```

So what? Now you know the distance to the destination, so after the agent moved (successfully) you can have a conditional node (a decorator) where you say if distance <= 50 execute whatever you have to execute. 

I think the last option makes the most sense, because why setting a leaf to a running state if it's not running? You are gonna call it every frame, so it is gonna run and complete successfully at each frame. The action is to "take one step", not to reach the goal, so it is successful at each step :)

(I'm assuming you know how to use yield, but if you don't I suggest you to check the documentation in the GDScript Basics page, at 'Yield and Coroutines'. On top of that, I suggest you to check the two script templates I included, where you find an example on how to do all the things you might wanna do with leaves and decorators.)

This whole process is gonna change in 1.2.0, where I plan to use the run() method for consistency and to even allow aborting running states, but until then this is how it works. I will try to make the future update so that it will not break your previous trees too much.

I hope I clarified your doubts and if you need more support feel free to ask :) I'm open to suggestions and change proposals if they are requested!

**Comment by ashfidable** [comment]
First of all, I would like to thank you so much for replying as soon as possible. You are a life savior for real and yes I am aware of yields (pretty powerful coroutines really). So, I did read the whole thing and honestly the last one works pretty well to me due to separation of distance check and the whole move_towards_position thing. Happy to say, it's working great here.

_My bad about velocity.normalized() thing, it was from my main project and I had to cut out most of the code to paste it here for easy debugging - sadly forgot to take that off haha_

Honestly, I do like this idle_frame and physics_frame thing. It looks nicer but that is no surprise that many here are used to physics_process and process instead. However, I am happy either way and loving the fact that you are catering towards user experience more. 

Coming to think of it, how would you go about implementing patrol between x number of points?
I was trying it now and most probably my head isn't working due to sleep but here's how I structured it for now.

* _BT_
* _BTSequence_
  * _BTSequence_
    * **AssignPoints** (Assigning a point from waypoint_list to a blackboard key called current_point)
    * **GoToPosition** (Same thing as above but instead of hardcoded Vector2, its referring to current_point key)
    * **Distance Check** (Decorator)
      * **_AssignAnotherPoint_**? (But then this will get changed when it repeats the tree again, so it's pretty pointless here)

Why the awful suggestion for the second AssignAnotherPoint was because the first AssignPoint keeps on repeating itself, so the current point keeps on changing. Let me quickly type out basic code for choosing a point from list

**change_points.gd**
```swift
extends BTLeaf


export (Array, NodePath) var waypoint
var curr_point = 0


func _tick(agent: Node, blackboard: Blackboard) -> bool:
	curr_point = (curr_point + 1) % waypoint.size()
	blackboard.set_data('current_point', get_node(waypoint[curr_point]))
	return succeed()
```

_Also, is it weird to say I am hyped about 1.2.0 than Godot 4.0?_  - you are killing it with the updates. When do you think that's going to come and will it change fundamentally when supporting nodes? Although, that's not an issue. Logic anyways in every node stays the same for sure. So, it's hardly any problem haha.

**Comment by GabrieleTorini** [comment]
The first thing I can suggest is to think of this in the opposite order, first check if it's reached, and move if it's not.
So basically:

-BTSelector
- - IsPointRechedOrNull? (extends BTDecorator) 
- - - AssignPoint
- - Move
